export type ItemType = "weapon" | "armor" | "accessory";
export type ItemRarity = "common" | "rare" | "epic" | "legendary" | "mythic";

export interface EquipmentItem {
  item_id: string;
  item_name: string;
  type: ItemType;
  rarity: ItemRarity;
  bonus_str: number;
  bonus_agi: number;
  bonus_vit: number;
  bonus_luk: number;
  bonus_hp: number;
  granted_skill_name?: string;
  granted_skill_icon?: string;
  icon: string;
  image_url: string;
  description: string;
}

export interface InventoryRecord {
  inventory_id: string;
  user_id: string;
  item_id: string;
  is_equipped: boolean;
  item: EquipmentItem;
}

export const EQUIPMENT_DICTIONARY: EquipmentItem[] = [
  {
    item_id: "e1010001-0000-0000-0000-000000000001",
    item_name: "Rusty Iron Broadsword",
    type: "weapon",
    rarity: "common",
    bonus_str: 10,
    bonus_agi: 0,
    bonus_vit: 5,
    bonus_luk: 0,
    bonus_hp: 50,
    granted_skill_name: "Iron Slash",
    icon: "sword",
    image_url: "/assets/items/weapons/rusty-sword.png",
    description: "A heavy, battered blade forged from simple iron.",
  },
  {
    item_id: "e1010002-0000-0000-0000-000000000002",
    item_name: "Novice Defender Shield",
    type: "armor",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 5,
    bonus_vit: 15,
    bonus_luk: 2,
    bonus_hp: 120,
    icon: "shield",
    image_url: "/assets/items/shields/wooden-shield.png",
    description: "Basic wooden shield providing fundamental physical blocking.",
  },
  {
    item_id: "e1010003-0000-0000-0000-000000000003",
    item_name: "Copper Amulet",
    type: "accessory",
    rarity: "common",
    bonus_str: 2,
    bonus_agi: 2,
    bonus_vit: 2,
    bonus_luk: 5,
    bonus_hp: 30,
    icon: "heart",
    image_url: "/assets/items/amulets/copper-amulet.png",
    description: "A tarnished copper charm said to grant minor luck.",
  },
  {
    item_id: "e1010004-0000-0000-0000-000000000013",
    item_name: "Wooden Training Staff",
    type: "weapon",
    rarity: "common",
    bonus_str: 6,
    bonus_agi: 8,
    bonus_vit: 2,
    bonus_luk: 2,
    bonus_hp: 40,
    icon: "sword",
    image_url: "/assets/items/weapons/training-staff.png",
    description: "Simple wooden staff used by novice martial artists.",
  },
  {
    item_id: "e1010005-0000-0000-0000-000000000014",
    item_name: "Recurve Scout Bow",
    type: "weapon",
    rarity: "common",
    bonus_str: 4,
    bonus_agi: 14,
    bonus_vit: 0,
    bonus_luk: 4,
    bonus_hp: 35,
    icon: "zap",
    image_url: "/assets/items/weapons/scout-bow.png",
    description: "Flexible wooden bow crafted for forest rangers.",
  },
  {
    item_id: "e1010006-0000-0000-0000-000000000015",
    item_name: "Padded Leather Tunic",
    type: "armor",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 8,
    bonus_vit: 12,
    bonus_luk: 0,
    bonus_hp: 100,
    icon: "shield",
    image_url: "/assets/items/shields/leather-tunic.png",
    description: "Light armor crafted from toughened hide.",
  },
  {
    item_id: "e1010007-0000-0000-0000-000000000016",
    item_name: "Apprentice Cloth Robe",
    type: "armor",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 4,
    bonus_vit: 8,
    bonus_luk: 10,
    bonus_hp: 80,
    icon: "sparkles",
    image_url: "/assets/items/shields/cloth-robe.png",
    description: "Comfortable tunic worn by novice spellcasters.",
  },
  {
    item_id: "e1010008-0000-0000-0000-000000000017",
    item_name: "Iron Ring of Power",
    type: "accessory",
    rarity: "common",
    bonus_str: 6,
    bonus_agi: 0,
    bonus_vit: 4,
    bonus_luk: 0,
    bonus_hp: 40,
    icon: "flame",
    image_url: "/assets/items/amulets/iron-ring.png",
    description: "Solid iron band granting steady physical power.",
  },
  {
    item_id: "e1010009-0000-0000-0000-000000000018",
    item_name: "Feathered Wind Anklet",
    type: "accessory",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 10,
    bonus_vit: 0,
    bonus_luk: 4,
    bonus_hp: 35,
    icon: "zap",
    image_url: "/assets/items/amulets/wind-anklet.png",
    description: "Enchanted anklet boosting agility and footwork.",
  },
  {
    item_id: "e1020001-0000-0000-0000-000000000004",
    item_name: "Shadow Steel Katana",
    type: "weapon",
    rarity: "rare",
    bonus_str: 28,
    bonus_agi: 22,
    bonus_vit: 5,
    bonus_luk: 10,
    bonus_hp: 180,
    granted_skill_name: "Shadow Strike",
    icon: "sword",
    image_url: "/assets/items/weapons/shadow-katana.png",
    description: "Razor-sharp blade infused with dark steel.",
  },
  {
    item_id: "e1020002-0000-0000-0000-000000000005",
    item_name: "Guardian Heavy Shield",
    type: "armor",
    rarity: "rare",
    bonus_str: 8,
    bonus_agi: 0,
    bonus_vit: 40,
    bonus_luk: 5,
    bonus_hp: 350,
    granted_skill_name: "Iron Fortress",
    icon: "shield",
    image_url: "/assets/items/shields/guardian-shield.png",
    description: "Reinforced iron shield forged for Vanguard defenders.",
  },
  {
    item_id: "e1020003-0000-0000-0000-000000000006",
    item_name: "Ring of Swiftness",
    type: "accessory",
    rarity: "rare",
    bonus_str: 0,
    bonus_agi: 35,
    bonus_vit: 10,
    bonus_luk: 15,
    bonus_hp: 150,
    icon: "zap",
    image_url: "/assets/items/amulets/swiftness-ring.png",
    description: "Lightweight silver ring that accelerates reflexes.",
  },
  {
    item_id: "e1020004-0000-0000-0000-000000000019",
    item_name: "Flame Twin Daggers",
    type: "weapon",
    rarity: "rare",
    bonus_str: 20,
    bonus_agi: 30,
    bonus_vit: 0,
    bonus_luk: 12,
    bonus_hp: 140,
    granted_skill_name: "Flame Burst",
    icon: "flame",
    image_url: "/assets/items/weapons/flame-daggers.png",
    description: "Pair of obsidian daggers burning with intense heat.",
  },
  {
    item_id: "e1020005-0000-0000-0000-000000000020",
    item_name: "Heavy Thor Warhammer",
    type: "weapon",
    rarity: "rare",
    bonus_str: 42,
    bonus_agi: 0,
    bonus_vit: 18,
    bonus_luk: 5,
    bonus_hp: 220,
    granted_skill_name: "Ground Smash",
    icon: "sword",
    image_url: "/assets/items/weapons/heavy-hammer.png",
    description: "Massive warhammer capable of shattering armor.",
  },
  {
    item_id: "e1020006-0000-0000-0000-000000000021",
    item_name: "Mithril Scaled Chainmail",
    type: "armor",
    rarity: "rare",
    bonus_str: 15,
    bonus_agi: 10,
    bonus_vit: 35,
    bonus_luk: 5,
    bonus_hp: 300,
    icon: "shield",
    image_url: "/assets/items/shields/mithril-chain.png",
    description: "Lightweight mithril armor balancing defense and mobility.",
  },
  {
    item_id: "e1020007-0000-0000-0000-000000000022",
    item_name: "Vampire Ruby Ring",
    type: "accessory",
    rarity: "rare",
    bonus_str: 18,
    bonus_agi: 12,
    bonus_vit: 18,
    bonus_luk: 10,
    bonus_hp: 200,
    icon: "heart",
    image_url: "/assets/items/amulets/ruby-ring.png",
    description: "Crimson ring absorbing vitality from defeated foes.",
  },
  {
    item_id: "e1020008-0000-0000-0000-000000000023",
    item_name: "Lucky Gold Coin Medallion",
    type: "accessory",
    rarity: "rare",
    bonus_str: 5,
    bonus_agi: 5,
    bonus_vit: 5,
    bonus_luk: 45,
    bonus_hp: 120,
    icon: "sparkles",
    image_url: "/assets/items/amulets/gold-coin.png",
    description: "Enchanted medallion dramatically boosting loot drop luck.",
  },
  {
    item_id: "e1030001-0000-0000-0000-000000000007",
    item_name: "Plasma Greatsword EX",
    type: "weapon",
    rarity: "epic",
    bonus_str: 60,
    bonus_agi: 30,
    bonus_vit: 35,
    bonus_luk: 25,
    bonus_hp: 500,
    granted_skill_name: "Plasma Overload",
    icon: "zap",
    image_url: "/assets/items/weapons/plasma-greatsword.png",
    description: "Futuristic blade glowing with supercharged plasma energy.",
  },
  {
    item_id: "e1030002-0000-0000-0000-000000000008",
    item_name: "Titanium Cyber Shield",
    type: "armor",
    rarity: "epic",
    bonus_str: 25,
    bonus_agi: 15,
    bonus_vit: 75,
    bonus_luk: 20,
    bonus_hp: 750,
    granted_skill_name: "Nanite Shield",
    icon: "shield",
    image_url: "/assets/items/shields/cyber-aegis.png",
    description: "Futuristic titanium barrier with self-repair nanite drones.",
  },
  {
    item_id: "e1030003-0000-0000-0000-000000000011",
    item_name: "Aether Celestial Talisman",
    type: "accessory",
    rarity: "epic",
    bonus_str: 30,
    bonus_agi: 45,
    bonus_vit: 30,
    bonus_luk: 40,
    bonus_hp: 400,
    icon: "sparkles",
    image_url: "/assets/items/amulets/aether-talisman.png",
    description: "Mystical amulet humming with celestial energy.",
  },
  {
    item_id: "e1030004-0000-0000-0000-000000000024",
    item_name: "Frostbite Glacial Spear",
    type: "weapon",
    rarity: "epic",
    bonus_str: 48,
    bonus_agi: 48,
    bonus_vit: 20,
    bonus_luk: 20,
    bonus_hp: 450,
    granted_skill_name: "Ice Lance",
    icon: "zap",
    image_url: "/assets/items/weapons/glacial-spear.png",
    description: "Crystalline spear frozen in eternal sub-zero ice.",
  },
  {
    item_id: "e1030005-0000-0000-0000-000000000025",
    item_name: "Berserker Dragon Cuirass",
    type: "armor",
    rarity: "epic",
    bonus_str: 35,
    bonus_agi: 15,
    bonus_vit: 65,
    bonus_luk: 15,
    bonus_hp: 650,
    granted_skill_name: "Dragon Rage",
    icon: "shield",
    image_url: "/assets/items/shields/dragon-cuirass.png",
    description: "Heavy plate forged from red dragon chest plates.",
  },
  {
    item_id: "e1030006-0000-0000-0000-000000000026",
    item_name: "Phoenix Flame Ring",
    type: "accessory",
    rarity: "epic",
    bonus_str: 35,
    bonus_agi: 25,
    bonus_vit: 25,
    bonus_luk: 35,
    bonus_hp: 500,
    icon: "flame",
    image_url: "/assets/items/amulets/phoenix-ring.png",
    description: "Ring imbued with the rebirth flame of the eternal phoenix.",
  },
  {
    item_id: "e1040001-0000-0000-0000-000000000009",
    item_name: "Void Relic Slayer",
    type: "weapon",
    rarity: "legendary",
    bonus_str: 125,
    bonus_agi: 75,
    bonus_vit: 60,
    bonus_luk: 60,
    bonus_hp: 1200,
    granted_skill_name: "Void Nova Buster",
    icon: "flame",
    image_url: "/assets/items/weapons/void-slayer.png",
    description: "Mythical blade forged in the abyss, capable of tearing reality.",
  },
  {
    item_id: "e1040002-0000-0000-0000-000000000010",
    item_name: "Dragon Scale Greatshield",
    type: "armor",
    rarity: "legendary",
    bonus_str: 50,
    bonus_agi: 35,
    bonus_vit: 140,
    bonus_luk: 45,
    bonus_hp: 1800,
    granted_skill_name: "Dragon Roar",
    icon: "shield",
    image_url: "/assets/items/shields/dragon-scale.png",
    description: "Impenetrable shield crafted from ancient dragon scales.",
  },
  {
    item_id: "e1040003-0000-0000-0000-000000000012",
    item_name: "Void Star Pendant",
    type: "accessory",
    rarity: "legendary",
    bonus_str: 60,
    bonus_agi: 80,
    bonus_vit: 60,
    bonus_luk: 90,
    bonus_hp: 800,
    icon: "sparkles",
    image_url: "/assets/items/amulets/void-pendant.png",
    description: "An ancient artifact containing the power of a collapsed star.",
  },
  {
    item_id: "e1040004-0000-0000-0000-000000000027",
    item_name: "Sunfire Holy Excalibur",
    type: "weapon",
    rarity: "legendary",
    bonus_str: 150,
    bonus_agi: 50,
    bonus_vit: 70,
    bonus_luk: 60,
    bonus_hp: 1400,
    granted_skill_name: "Divine Judgment",
    icon: "sword",
    image_url: "/assets/items/weapons/holy-excalibur.png",
    description: "Radiant holy blade capable of purifying any dark boss.",
  },
  {
    item_id: "e1040005-0000-0000-0000-000000000028",
    item_name: "Aegis of Immortality",
    type: "armor",
    rarity: "legendary",
    bonus_str: 40,
    bonus_agi: 40,
    bonus_vit: 180,
    bonus_luk: 50,
    bonus_hp: 2500,
    granted_skill_name: "Resurrection Shield",
    icon: "shield",
    image_url: "/assets/items/shields/immortal-aegis.png",
    description: "Divine shield forged by ancient gods granting infinite defense.",
  },
  {
    item_id: "e1040006-0000-0000-0000-000000000029",
    item_name: "Infinity Eye Ring",
    type: "accessory",
    rarity: "legendary",
    bonus_str: 70,
    bonus_agi: 70,
    bonus_vit: 70,
    bonus_luk: 120,
    bonus_hp: 1000,
    granted_skill_name: "Infinity Luck",
    icon: "sparkles",
    image_url: "/assets/items/amulets/infinity-ring.png",
    description: "Cosmic ring bestowing ultimate critical strikes and fortune.",
  },
  {
    item_id: "e1050001-0000-0000-0000-000000000030",
    item_name: "Quantum Singularity Cannon",
    type: "weapon",
    rarity: "mythic",
    bonus_str: 220,
    bonus_agi: 120,
    bonus_vit: 80,
    bonus_luk: 100,
    bonus_hp: 2000,
    granted_skill_name: "Singularity Obliteration",
    icon: "zap",
    image_url: "/assets/items/weapons/singularity-cannon.png",
    description: "Godly weapon unleashing miniature black holes upon foes.",
  },
  {
    item_id: "e1050002-0000-0000-0000-000000000031",
    item_name: "Nether Core Exosuit",
    type: "armor",
    rarity: "mythic",
    bonus_str: 100,
    bonus_agi: 80,
    bonus_vit: 250,
    bonus_luk: 80,
    bonus_hp: 3500,
    granted_skill_name: "Absolute Barrier",
    icon: "shield",
    image_url: "/assets/items/shields/nether-exosuit.png",
    description: "Apocalyptic mechanical suit powered by nether star energy.",
  },
  {
    item_id: "e1050003-0000-0000-0000-000000000032",
    item_name: "Crown of the Sovereign Titan",
    type: "accessory",
    rarity: "mythic",
    bonus_str: 120,
    bonus_agi: 120,
    bonus_vit: 120,
    bonus_luk: 180,
    bonus_hp: 2000,
    granted_skill_name: "Titan Sovereign",
    icon: "sparkles",
    image_url: "/assets/items/amulets/titan-crown.png",
    description: "Supreme crown worn by the master of all pixel realms.",
  },
];
