export type ItemType = "weapon" | "armor" | "accessory";
export type ItemRarity = "common" | "rare" | "epic" | "legendary" | "mythic";

export interface EquipmentItem {
  item_id: string;
  item_name: string;
  type: ItemType;
  rarity: ItemRarity;
  bonus_str: number;
  bonus_agi: number;
  bonus_vit: number;
  bonus_luk: number;
  bonus_hp: number;
  granted_skill_name?: string;
  granted_skill_icon?: string;
  icon: string;
  image_url: string;
  description: string;
}

export interface InventoryRecord {
  inventory_id: string;
  user_id: string;
  item_id: string;
  is_equipped: boolean;
  item: EquipmentItem;
}

export const EQUIPMENT_DICTIONARY: EquipmentItem[] = [
  {
    item_id: "e1010001-0000-0000-0000-000000000001",
    item_name: "Rusty Iron Broadsword",
    type: "weapon",
    rarity: "common",
    bonus_str: 15,
    bonus_agi: 0,
    bonus_vit: 5,
    bonus_luk: 0,
    bonus_hp: 50,
    granted_skill_name: "Heavy Slash",
    granted_skill_icon: "/assets/skills/swordsman/Icon1.png",
    icon: "sword",
    image_url: "/assets/items/weapons/Icon1.png",
    description: "A heavy, battered blade forged from simple iron.",
  },
  {
    item_id: "e1010002-0000-0000-0000-000000000002",
    item_name: "Novice Defender Shield",
    type: "armor",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 5,
    bonus_vit: 20,
    bonus_luk: 2,
    bonus_hp: 150,
    granted_skill_name: "Shield Counter",
    granted_skill_icon: "/assets/skills/swordsman/Icon2.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon1.png",
    description: "Basic wooden shield providing fundamental physical blocking.",
  },
  {
    item_id: "e1010003-0000-0000-0000-000000000003",
    item_name: "Copper Amulet",
    type: "accessory",
    rarity: "common",
    bonus_str: 8,
    bonus_agi: 8,
    bonus_vit: 8,
    bonus_luk: 18,
    bonus_hp: 100,
    granted_skill_name: "Lucky Charm",
    granted_skill_icon: "/assets/skills/undead/Icon3.png",
    icon: "heart",
    image_url: "/assets/items/amulets/Icon25.png",
    description: "A tarnished copper charm granting minor luck and stats.",
  },
  {
    item_id: "e1010004-0000-0000-0000-000000000013",
    item_name: "Wooden Training Staff",
    type: "weapon",
    rarity: "common",
    bonus_str: 10,
    bonus_agi: 12,
    bonus_vit: 2,
    bonus_luk: 2,
    bonus_hp: 40,
    granted_skill_name: "Staff Strike",
    granted_skill_icon: "/assets/skills/swordsman/Icon4.png",
    icon: "sword",
    image_url: "/assets/items/weapons/Icon2.png",
    description: "Simple wooden staff used by novice martial artists.",
  },
  {
    item_id: "e1010005-0000-0000-0000-000000000014",
    item_name: "Recurve Scout Bow",
    type: "weapon",
    rarity: "common",
    bonus_str: 8,
    bonus_agi: 18,
    bonus_vit: 0,
    bonus_luk: 6,
    bonus_hp: 35,
    granted_skill_name: "Quick Arrow",
    granted_skill_icon: "/assets/skills/swordsman/Icon5.png",
    icon: "zap",
    image_url: "/assets/items/weapons/Icon3.png",
    description: "Flexible wooden bow crafted for forest rangers.",
  },
  {
    item_id: "e1010006-0000-0000-0000-000000000015",
    item_name: "Padded Leather Tunic",
    type: "armor",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 12,
    bonus_vit: 18,
    bonus_luk: 0,
    bonus_hp: 120,
    granted_skill_name: "Evade Stance",
    granted_skill_icon: "/assets/skills/swordsman/Icon6.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon2.png",
    description: "Light armor crafted from toughened hide.",
  },
  {
    item_id: "e1010007-0000-0000-0000-000000000016",
    item_name: "Apprentice Cloth Robe",
    type: "armor",
    rarity: "common",
    bonus_str: 0,
    bonus_agi: 8,
    bonus_vit: 14,
    bonus_luk: 15,
    bonus_hp: 100,
    granted_skill_name: "Mana Shield",
    granted_skill_icon: "/assets/skills/undead/Icon7.png",
    icon: "sparkles",
    image_url: "/assets/items/shields/Icon3.png",
    description: "Comfortable tunic worn by novice spellcasters.",
  },
  {
    item_id: "e1010008-0000-0000-0000-000000000017",
    item_name: "Iron Ring of Power",
    type: "accessory",
    rarity: "common",
    bonus_str: 20,
    bonus_agi: 5,
    bonus_vit: 15,
    bonus_luk: 5,
    bonus_hp: 120,
    granted_skill_name: "Iron Surge",
    granted_skill_icon: "/assets/skills/swordsman/Icon8.png",
    icon: "flame",
    image_url: "/assets/items/amulets/Icon26.png",
    description: "Solid iron band granting steady physical strength.",
  },
  {
    item_id: "e1010009-0000-0000-0000-000000000018",
    item_name: "Feathered Wind Anklet",
    type: "accessory",
    rarity: "common",
    bonus_str: 5,
    bonus_agi: 25,
    bonus_vit: 5,
    bonus_luk: 15,
    bonus_hp: 100,
    granted_skill_name: "Wind Haste",
    granted_skill_icon: "/assets/skills/swordsman/Icon9.png",
    icon: "zap",
    image_url: "/assets/items/amulets/Icon27.png",
    description: "Enchanted anklet boosting agility and footwork.",
  },
  {
    item_id: "e1020001-0000-0000-0000-000000000004",
    item_name: "Shadow Steel Katana",
    type: "weapon",
    rarity: "rare",
    bonus_str: 35,
    bonus_agi: 25,
    bonus_vit: 10,
    bonus_luk: 12,
    bonus_hp: 200,
    granted_skill_name: "Shadow Slash EX",
    granted_skill_icon: "/assets/skills/swordsman/Icon10.png",
    icon: "sword",
    image_url: "/assets/items/weapons/Icon10.png",
    description: "Razor-sharp blade infused with dark steel.",
  },
  {
    item_id: "e1020002-0000-0000-0000-000000000005",
    item_name: "Guardian Heavy Shield",
    type: "armor",
    rarity: "rare",
    bonus_str: 10,
    bonus_agi: 0,
    bonus_vit: 50,
    bonus_luk: 8,
    bonus_hp: 450,
    granted_skill_name: "Iron Fortress Blast",
    granted_skill_icon: "/assets/skills/swordsman/Icon11.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon4.png",
    description: "Reinforced iron shield forged for Vanguard defenders.",
  },
  {
    item_id: "e1020003-0000-0000-0000-000000000006",
    item_name: "Ring of Swiftness",
    type: "accessory",
    rarity: "rare",
    bonus_str: 15,
    bonus_agi: 55,
    bonus_vit: 25,
    bonus_luk: 35,
    bonus_hp: 300,
    granted_skill_name: "Reflex Boost",
    granted_skill_icon: "/assets/skills/swordsman/Icon12.png",
    icon: "zap",
    image_url: "/assets/items/amulets/Icon28.png",
    description: "Lightweight silver ring that accelerates reflexes.",
  },
  {
    item_id: "e1020004-0000-0000-0000-000000000019",
    item_name: "Flame Twin Daggers",
    type: "weapon",
    rarity: "rare",
    bonus_str: 30,
    bonus_agi: 40,
    bonus_vit: 5,
    bonus_luk: 15,
    bonus_hp: 180,
    granted_skill_name: "Flame Dual Slash",
    granted_skill_icon: "/assets/skills/swordsman/Icon13.png",
    icon: "flame",
    image_url: "/assets/items/weapons/Icon13.png",
    description: "Pair of obsidian daggers burning with intense heat.",
  },
  {
    item_id: "e1020005-0000-0000-0000-000000000020",
    item_name: "Heavy Thor Warhammer",
    type: "weapon",
    rarity: "rare",
    bonus_str: 55,
    bonus_agi: 0,
    bonus_vit: 25,
    bonus_luk: 8,
    bonus_hp: 280,
    granted_skill_name: "Earth Shatter Smash",
    granted_skill_icon: "/assets/skills/swordsman/Icon14.png",
    icon: "sword",
    image_url: "/assets/items/weapons/Icon14.png",
    description: "Massive warhammer capable of shattering armor.",
  },
  {
    item_id: "e1020006-0000-0000-0000-000000000021",
    item_name: "Mithril Scaled Chainmail",
    type: "armor",
    rarity: "rare",
    bonus_str: 20,
    bonus_agi: 15,
    bonus_vit: 45,
    bonus_luk: 10,
    bonus_hp: 400,
    granted_skill_name: "Mithril Aegis",
    granted_skill_icon: "/assets/skills/swordsman/Icon15.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon5.png",
    description: "Lightweight mithril armor balancing defense and mobility.",
  },
  {
    item_id: "e1020007-0000-0000-0000-000000000022",
    item_name: "Vampire Ruby Ring",
    type: "accessory",
    rarity: "rare",
    bonus_str: 35,
    bonus_agi: 25,
    bonus_vit: 35,
    bonus_luk: 25,
    bonus_hp: 450,
    granted_skill_name: "Vampiric Drain",
    granted_skill_icon: "/assets/skills/undead/Icon16.png",
    icon: "heart",
    image_url: "/assets/items/amulets/Icon29.png",
    description: "Crimson ring absorbing vitality from defeated foes.",
  },
  {
    item_id: "e1020008-0000-0000-0000-000000000023",
    item_name: "Lucky Gold Coin Medallion",
    type: "accessory",
    rarity: "rare",
    bonus_str: 15,
    bonus_agi: 15,
    bonus_vit: 15,
    bonus_luk: 85,
    bonus_hp: 300,
    granted_skill_name: "Fortune Amulet",
    granted_skill_icon: "/assets/skills/undead/Icon17.png",
    icon: "sparkles",
    image_url: "/assets/items/amulets/Icon30.png",
    description: "Enchanted medallion dramatically boosting loot drop luck.",
  },
  {
    item_id: "e1030001-0000-0000-0000-000000000007",
    item_name: "Plasma Greatsword EX",
    type: "weapon",
    rarity: "epic",
    bonus_str: 80,
    bonus_agi: 40,
    bonus_vit: 45,
    bonus_luk: 30,
    bonus_hp: 600,
    granted_skill_name: "Plasma Cannon Slash",
    granted_skill_icon: "/assets/skills/swordsman/Icon18.png",
    icon: "zap",
    image_url: "/assets/items/weapons/Icon18.png",
    description: "Futuristic blade glowing with supercharged plasma energy.",
  },
  {
    item_id: "e1030002-0000-0000-0000-000000000008",
    item_name: "Titanium Cyber Shield",
    type: "armor",
    rarity: "epic",
    bonus_str: 30,
    bonus_agi: 20,
    bonus_vit: 95,
    bonus_luk: 25,
    bonus_hp: 950,
    granted_skill_name: "Nanite Shield Burst",
    granted_skill_icon: "/assets/skills/swordsman/Icon19.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon6.png",
    description: "Futuristic titanium barrier with self-repair nanite drones.",
  },
  {
    item_id: "e1030003-0000-0000-0000-000000000011",
    item_name: "Aether Celestial Talisman",
    type: "accessory",
    rarity: "epic",
    bonus_str: 55,
    bonus_agi: 75,
    bonus_vit: 55,
    bonus_luk: 75,
    bonus_hp: 750,
    granted_skill_name: "Celestial Glow",
    granted_skill_icon: "/assets/skills/undead/Icon20.png",
    icon: "sparkles",
    image_url: "/assets/items/amulets/Icon31.png",
    description: "Mystical amulet humming with celestial energy.",
  },
  {
    item_id: "e1030004-0000-0000-0000-000000000024",
    item_name: "Frostbite Glacial Spear",
    type: "weapon",
    rarity: "epic",
    bonus_str: 65,
    bonus_agi: 65,
    bonus_vit: 25,
    bonus_luk: 25,
    bonus_hp: 550,
    granted_skill_name: "Glacial Ice Stab",
    granted_skill_icon: "/assets/skills/swordsman/Icon21.png",
    icon: "zap",
    image_url: "/assets/items/weapons/Icon21.png",
    description: "Crystalline spear frozen in eternal sub-zero ice.",
  },
  {
    item_id: "e1030005-0000-0000-0000-000000000025",
    item_name: "Berserker Dragon Cuirass",
    type: "armor",
    rarity: "epic",
    bonus_str: 45,
    bonus_agi: 20,
    bonus_vit: 85,
    bonus_luk: 20,
    bonus_hp: 850,
    granted_skill_name: "Dragon Retaliation",
    granted_skill_icon: "/assets/skills/swordsman/Icon22.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon7.png",
    description: "Heavy plate forged from red dragon chest plates.",
  },
  {
    item_id: "e1030006-0000-0000-0000-000000000026",
    item_name: "Phoenix Flame Ring",
    type: "accessory",
    rarity: "epic",
    bonus_str: 65,
    bonus_agi: 50,
    bonus_vit: 50,
    bonus_luk: 65,
    bonus_hp: 800,
    granted_skill_name: "Phoenix Spark",
    granted_skill_icon: "/assets/skills/swordsman/Icon23.png",
    icon: "flame",
    image_url: "/assets/items/amulets/Icon32.png",
    description: "Ring imbued with the rebirth flame of the eternal phoenix.",
  },
  {
    item_id: "e1040001-0000-0000-0000-000000000009",
    item_name: "Void Relic Slayer",
    type: "weapon",
    rarity: "legendary",
    bonus_str: 160,
    bonus_agi: 95,
    bonus_vit: 75,
    bonus_luk: 75,
    bonus_hp: 1500,
    granted_skill_name: "Void Annihilation Nova",
    granted_skill_icon: "/assets/skills/undead/Icon24.png",
    icon: "flame",
    image_url: "/assets/items/weapons/Icon24.png",
    description: "Mythical blade forged in the abyss, capable of tearing reality.",
  },
  {
    item_id: "e1040002-0000-0000-0000-000000000010",
    item_name: "Dragon Scale Greatshield",
    type: "armor",
    rarity: "legendary",
    bonus_str: 65,
    bonus_agi: 45,
    bonus_vit: 175,
    bonus_luk: 55,
    bonus_hp: 2400,
    granted_skill_name: "Dragon Roar Counter",
    granted_skill_icon: "/assets/skills/swordsman/Icon25.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon8.png",
    description: "Impenetrable shield crafted from ancient dragon scales.",
  },
  {
    item_id: "e1040003-0000-0000-0000-000000000012",
    item_name: "Void Star Pendant",
    type: "accessory",
    rarity: "legendary",
    bonus_str: 95,
    bonus_agi: 125,
    bonus_vit: 95,
    bonus_luk: 145,
    bonus_hp: 1400,
    granted_skill_name: "Starlight Aura",
    granted_skill_icon: "/assets/skills/undead/Icon26.png",
    icon: "sparkles",
    image_url: "/assets/items/amulets/Icon33.png",
    description: "An ancient artifact containing the power of a collapsed star.",
  },
  {
    item_id: "e1040004-0000-0000-0000-000000000027",
    item_name: "Sunfire Holy Excalibur",
    type: "weapon",
    rarity: "legendary",
    bonus_str: 185,
    bonus_agi: 65,
    bonus_vit: 85,
    bonus_luk: 75,
    bonus_hp: 1700,
    granted_skill_name: "Divine Holy Judgment",
    granted_skill_icon: "/assets/skills/swordsman/Icon27.png",
    icon: "sword",
    image_url: "/assets/items/weapons/Icon27.png",
    description: "Radiant holy blade capable of purifying any dark boss.",
  },
  {
    item_id: "e1040005-0000-0000-0000-000000000028",
    item_name: "Aegis of Immortality",
    type: "armor",
    rarity: "legendary",
    bonus_str: 55,
    bonus_agi: 55,
    bonus_vit: 220,
    bonus_luk: 65,
    bonus_hp: 3200,
    granted_skill_name: "Immortal Barrier",
    granted_skill_icon: "/assets/skills/swordsman/Icon28.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon9.png",
    description: "Divine shield forged by ancient gods granting infinite defense.",
  },
  {
    item_id: "e1040006-0000-0000-0000-000000000029",
    item_name: "Infinity Eye Ring",
    type: "accessory",
    rarity: "legendary",
    bonus_str: 100,
    bonus_agi: 100,
    bonus_vit: 100,
    bonus_luk: 180,
    bonus_hp: 1600,
    granted_skill_name: "Infinity Blessing",
    granted_skill_icon: "/assets/skills/undead/Icon29.png",
    icon: "sparkles",
    image_url: "/assets/items/amulets/Icon34.png",
    description: "Cosmic ring bestowing ultimate critical strikes and fortune.",
  },
  {
    item_id: "e1050001-0000-0000-0000-000000000030",
    item_name: "Quantum Singularity Cannon",
    type: "weapon",
    rarity: "mythic",
    bonus_str: 260,
    bonus_agi: 140,
    bonus_vit: 100,
    bonus_luk: 120,
    bonus_hp: 2500,
    granted_skill_name: "Quantum Obliteration",
    granted_skill_icon: "/assets/skills/swordsman/Icon30.png",
    icon: "zap",
    image_url: "/assets/items/weapons/Icon30.png",
    description: "Godly weapon unleashing miniature black holes upon foes.",
  },
  {
    item_id: "e1050002-0000-0000-0000-000000000031",
    item_name: "Nether Core Exosuit",
    type: "armor",
    rarity: "mythic",
    bonus_str: 120,
    bonus_agi: 95,
    bonus_vit: 300,
    bonus_luk: 95,
    bonus_hp: 4500,
    granted_skill_name: "Nether Core Barrier",
    granted_skill_icon: "/assets/skills/undead/Icon31.png",
    icon: "shield",
    image_url: "/assets/items/shields/Icon10.png",
    description: "Apocalyptic mechanical suit powered by nether star energy.",
  },
  {
    item_id: "e1050003-0000-0000-0000-000000000032",
    item_name: "Crown of the Sovereign Titan",
    type: "accessory",
    rarity: "mythic",
    bonus_str: 180,
    bonus_agi: 180,
    bonus_vit: 180,
    bonus_luk: 250,
    bonus_hp: 3000,
    granted_skill_name: "Sovereign Grace",
    granted_skill_icon: "/assets/skills/undead/Icon32.png",
    icon: "sparkles",
    image_url: "/assets/items/amulets/Icon35.png",
    description: "Supreme crown worn by the master of all pixel realms.",
  },
];
