export interface ExerciseDefinition {
  id: string;
  name: string;
  category: "Chest" | "Back" | "Legs" | "Shoulders" | "Arms" | "Core" | "Cardio";
  difficultyRank: number;
  difficultyLabel: "Novice" | "Intermediate" | "Advanced" | "Master";
  equipment: "Barbell" | "Dumbbell" | "Bodyweight" | "Machine" | "Cable";
  targetMuscles: string[];
  instructions: string[];
  rvsMultiplier: number;
}

export const EXERCISE_DATABASE: ExerciseDefinition[] = [
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Pectoralis Major", "Triceps Brachii", "Anterior Deltoids"],
    instructions: [
      "Lie flat on the bench with feet firm on the floor and grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and lower it with control to the mid-chest while keeping elbows at a 45-degree angle.",
      "Press the bar explosively back to starting position without locking out elbows abruptly.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    category: "Legs",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Quadriceps", "Gluteus Maximus", "Hamstrings", "Erector Spinae"],
    instructions: [
      "Position the barbell across upper traps, unrack, and step back with feet shoulder-width apart.",
      "Inhale, brace your core, and bend hips and knees to descend until thighs are parallel to the ground.",
      "Drive through your mid-foot and heels to return upward while keeping chest upright.",
    ],
    rvsMultiplier: 1.15,
  },
  {
    id: "barbell-deadlift",
    name: "Barbell Conventional Deadlift",
    category: "Back",
    difficultyRank: 5,
    difficultyLabel: "Master",
    equipment: "Barbell",
    targetMuscles: ["Erector Spinae", "Hamstrings", "Glutes", "Latissimus Dorsi", "Trapezius"],
    instructions: [
      "Stand with feet hip-width apart with the barbell over mid-foot. Hinge at hips to grab the bar.",
      "Flatten your back, engage lats, take a deep breath, and pull slack out of the bar.",
      "Drive through legs and push floor away, standing tall without hyperextending lower back at top.",
    ],
    rvsMultiplier: 1.25,
  },
  {
    id: "overhead-press",
    name: "Barbell Standing Overhead Press",
    category: "Shoulders",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Anterior Deltoids", "Lateral Deltoids", "Triceps", "Upper Chest", "Core"],
    instructions: [
      "Grip the bar slightly wider than shoulders and resting across collarbone with wrists neutral.",
      "Brace glutes and core, press bar straight up, tilting head back slightly until bar clears chin.",
      "Lock out overhead directly over shoulders and return down to collarbone with control.",
    ],
    rvsMultiplier: 1.05,
  },
  {
    id: "bent-over-barbell-row",
    name: "Bent-Over Barbell Row",
    category: "Back",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius", "Biceps Brachii"],
    instructions: [
      "Hinge forward at hips with knees slightly bent until torso is roughly at a 45-degree angle.",
      "Grip bar with overhand grip and pull bar toward lower abdomen, squeezing shoulder blades together.",
      "Lower bar slowly under control without swinging your upper torso.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "pull-up",
    name: "Bodyweight Pull-Up",
    category: "Back",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Latissimus Dorsi", "Biceps Brachii", "Rear Deltoids", "Core"],
    instructions: [
      "Grip pull-up bar with overhand grip wider than shoulders, hanging with straight arms.",
      "Depress shoulder blades and pull chin above the bar while driving elbows down toward ribcage.",
      "Lower body with full control back to dead-hang position.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "dumbbell-incline-press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Upper Pectoralis Major", "Anterior Deltoids", "Triceps"],
    instructions: [
      "Set bench at 30-degree incline. Sit with dumbbells resting on thighs, then kick them up to shoulders.",
      "Press dumbbells up over upper chest until arms are extended, palms facing forward.",
      "Lower dumbbells steadily until upper arms are parallel to the floor.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    category: "Legs",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Hamstrings", "Gluteus Maximus", "Lower Back"],
    instructions: [
      "Stand holding dumbbells in front of thighs with knees slightly unlocked.",
      "Push hips backward while lowering dumbbells down front of legs until feeling hamstring stretch.",
      "Contract glutes and hamstrings to drive hips forward back to standing position.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "Shoulders",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Lateral Deltoids"],
    instructions: [
      "Stand holding dumbbells at sides with slight bend in elbows.",
      "Raise arms out to sides until parallel with floor, keeping pinkies slightly higher than thumbs.",
      "Pause at top, then lower with control without using momentum.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "dumbbell-bicep-curl",
    name: "Standing Dumbbell Bicep Curl",
    category: "Arms",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Biceps Brachii", "Brachialis"],
    instructions: [
      "Hold dumbbells with arms fully extended and palms facing forward.",
      "Curl weights toward shoulders by contracting biceps while keeping upper arms stationary.",
      "Squeeze at peak contraction, then slowly lower back down.",
    ],
    rvsMultiplier: 0.75,
  },
  {
    id: "tricep-rope-pushdown",
    name: "Cable Tricep Rope Pushdown",
    category: "Arms",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Triceps Brachii (Lateral & Medial Heads)"],
    instructions: [
      "Attach rope to high pulley. Hold ends of rope with elbows tucked to sides.",
      "Extend arms down until fully straight, spreading rope ends apart at bottom.",
      "Slowly allow rope to return up to chest level without letting elbows drift forward.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Abdominal Leg Raise",
    category: "Core",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Rectus Abdominis", "Hip Flexors", "Obliques"],
    instructions: [
      "Hang from pull-up bar with overhand grip and legs straight.",
      "Engage core and raise legs until parallel to floor without swinging torso.",
      "Lower legs back down slowly to complete 1 rep.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "step-jack-cardio",
    name: "Step Jack Plyometric Cardio",
    category: "Cardio",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Quadriceps", "Glutes", "Shoulders", "Core"],
    instructions: [
      "Stand upright with feet together and arms at your sides.",
      "Step right foot out to the side while swinging both arms up above head.",
      "Return right foot to center and lower arms, then repeat on left side rhythmically.",
    ],
    rvsMultiplier: 0.7,
  },
];
