export interface ExerciseDefinition {
  id: string;
  name: string;
  category: "Chest" | "Back" | "Legs" | "Shoulders" | "Arms" | "Core" | "Cardio";
  difficultyRank: number;
  difficultyLabel: "Novice" | "Intermediate" | "Advanced" | "Master";
  equipment: "Barbell" | "Dumbbell" | "Bodyweight" | "Machine" | "Cable";
  targetMuscles: string[];
  instructions: string[];
  rvsMultiplier: number;
}

export const EXERCISE_DATABASE: ExerciseDefinition[] = [
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Pectoralis Major", "Triceps Brachii", "Anterior Deltoids"],
    instructions: [
      "Lie flat on the bench with feet firm on the floor and grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and lower it with control to mid-chest while keeping elbows tucked at a 45-degree angle.",
      "Press the bar explosively back to starting position without locking out elbows abruptly.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "dumbbell-incline-press",
    name: "Incline Dumbbell Chest Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Upper Pectoralis Major", "Anterior Deltoids", "Triceps"],
    instructions: [
      "Set bench at 30-degree incline. Sit with dumbbells resting on thighs, then kick them up to shoulders.",
      "Press dumbbells up over upper chest until arms are extended, palms facing forward.",
      "Lower dumbbells steadily until upper arms are parallel to the floor.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "decline-bench-press",
    name: "Decline Barbell Bench Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Lower Pectoralis Major", "Triceps Brachii"],
    instructions: [
      "Secure legs in decline bench. Grip bar with medium width.",
      "Unrack and lower bar smoothly to lower sternum.",
      "Press bar straight up until arms are extended.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "wide-push-up",
    name: "Wide Grip Push-Up",
    category: "Chest",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Outer Chest", "Anterior Deltoids", "Core"],
    instructions: [
      "Place hands on the floor wider than shoulder-width apart.",
      "Lower body until chest almost touches the floor, keeping core rigid.",
      "Push back up to starting position.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "dumbbell-chest-flye",
    name: "Dumbbell Chest Flye",
    category: "Chest",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Pectoralis Major", "Anterior Deltoids"],
    instructions: [
      "Lie on flat bench holding dumbbells overhead with palms facing each other.",
      "Lower dumbbells out to sides in a wide arc with elbows slightly bent until chest stretches.",
      "Squeeze chest muscles to bring dumbbells back together over chest.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "cable-crossover-flye",
    name: "Cable Crossover Chest Flye",
    category: "Chest",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Pectoralis Major (Lower & Inner Sternal Head)"],
    instructions: [
      "Stand in center of cable machine with high pulleys attached to handles.",
      "Pull handles down and together in front of waist while keeping elbows slightly bent.",
      "Slowly return to start position under constant cable tension.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "parallel-bar-dips",
    name: "Chest Dips on Parallel Bars",
    category: "Chest",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Lower Chest", "Triceps Brachii", "Anterior Deltoids"],
    instructions: [
      "Hold parallel bars and support body weight with straight arms. Lean torso forward 30 degrees.",
      "Bend elbows and lower body until shoulders are below elbows.",
      "Drive through palms to push body back up to lock out.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "barbell-deadlift",
    name: "Barbell Conventional Deadlift",
    category: "Back",
    difficultyRank: 5,
    difficultyLabel: "Master",
    equipment: "Barbell",
    targetMuscles: ["Erector Spinae", "Hamstrings", "Glutes", "Latissimus Dorsi", "Trapezius"],
    instructions: [
      "Stand with feet hip-width apart with the barbell over mid-foot. Hinge at hips to grab the bar.",
      "Flatten back, engage lats, take a deep breath, and pull slack out of the bar.",
      "Drive through legs and push floor away, standing tall without hyperextending lower back.",
    ],
    rvsMultiplier: 1.25,
  },
  {
    id: "bent-over-barbell-row",
    name: "Bent-Over Barbell Row",
    category: "Back",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius", "Biceps Brachii"],
    instructions: [
      "Hinge forward at hips with knees slightly bent until torso is roughly at a 45-degree angle.",
      "Grip bar with overhand grip and pull bar toward lower abdomen, squeezing shoulder blades.",
      "Lower bar slowly under control without swinging upper torso.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "lat-pulldown-wide",
    name: "Wide-Grip Lat Pulldown",
    category: "Back",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Latissimus Dorsi", "Rear Deltoids", "Biceps"],
    instructions: [
      "Grip wide bar attachment with overhand grip and sit with thighs secured under pads.",
      "Pull bar down to upper chest while driving elbows down and back.",
      "Slowly release bar back up until lats are fully stretched.",
    ],
    rvsMultiplier: 0.9,
  },
  {
    id: "pull-up",
    name: "Bodyweight Pull-Up",
    category: "Back",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Latissimus Dorsi", "Biceps Brachii", "Rear Deltoids", "Core"],
    instructions: [
      "Grip pull-up bar with overhand grip wider than shoulders, hanging with straight arms.",
      "Depress shoulder blades and pull chin above the bar while driving elbows down.",
      "Lower body with full control back to dead-hang position.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    category: "Back",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Middle Trapezius", "Rhomboids", "Latissimus Dorsi"],
    instructions: [
      "Sit on rowing machine with feet on footplates and knees slightly bent.",
      "Pull V-bar handle toward navel while keeping chest high and squeezing back muscles.",
      "Return handle forward under control without rounding lower back.",
    ],
    rvsMultiplier: 0.9,
  },
  {
    id: "single-arm-dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    category: "Back",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Latissimus Dorsi", "Rhomboids", "Biceps"],
    instructions: [
      "Place one knee and hand on flat bench with flat back.",
      "Hold dumbbell in free hand and pull elbow straight up past torso.",
      "Lower dumbbell smoothly until arm is fully extended.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "t-bar-row",
    name: "T-Bar Landmine Row",
    category: "Back",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Middle Back", "Latissimus Dorsi", "Trapezius"],
    instructions: [
      "Straddle T-bar machine or landmine barbell. Hinge at hips.",
      "Grip handles and pull weight toward chest while retracting shoulder blades.",
      "Lower weight steadily back to starting position.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "back-hyperextension",
    name: "45-Degree Hyperextension",
    category: "Back",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Erector Spinae", "Glutes", "Hamstrings"],
    instructions: [
      "Lock ankles under footpads on hyperextension bench with hips resting on upper pad.",
      "Lower torso toward floor, then contract lower back and glutes to raise torso back in line with legs.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    category: "Legs",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Quadriceps", "Gluteus Maximus", "Hamstrings", "Erector Spinae"],
    instructions: [
      "Position barbell across upper traps, unrack, and step back with feet shoulder-width apart.",
      "Inhale, brace core, and bend hips and knees to descend until thighs are parallel to ground.",
      "Drive through mid-foot and heels to return upward while keeping chest upright.",
    ],
    rvsMultiplier: 1.15,
  },
  {
    id: "barbell-front-squat",
    name: "Barbell Front Squat",
    category: "Legs",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Quadriceps", "Core", "Glutes"],
    instructions: [
      "Rest bar across anterior deltoids with fingertips under bar and elbows held high.",
      "Squat down deeply while keeping elbows pointing forward to prevent bar from rolling.",
      "Drive up through legs back to standing.",
    ],
    rvsMultiplier: 1.15,
  },
  {
    id: "leg-press-machine",
    name: "Leg Press Machine",
    category: "Legs",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Quadriceps", "Gluteus Maximus", "Calves"],
    instructions: [
      "Sit in machine with back flat against pad and feet hip-width on sled platform.",
      "Unlatch safety bars and lower platform until knees are at 90-degree angle.",
      "Press platform back up through mid-foot without locking knees.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    category: "Legs",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Hamstrings", "Gluteus Maximus", "Lower Back"],
    instructions: [
      "Stand holding dumbbells in front of thighs with knees slightly unlocked.",
      "Push hips backward while lowering dumbbells down front of legs until feeling hamstring stretch.",
      "Contract glutes and hamstrings to drive hips forward back to standing.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "walking-lunges",
    name: "Walking Dumbbell Lunges",
    category: "Legs",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    instructions: [
      "Hold dumbbells at sides. Step forward with one leg and lower back knee toward floor.",
      "Drive off front foot to step directly into next lunge stride with opposite leg.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "leg-extension",
    name: "Machine Leg Extension",
    category: "Legs",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Quadriceps (Rectus Femoris & Vastus Lateralis)"],
    instructions: [
      "Sit on machine with back against pad and lower shin against roller pad.",
      "Extend legs forward until fully straight, squeezing quads at top.",
      "Lower pad back down with control.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl Machine",
    category: "Legs",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Hamstrings (Biceps Femoris & Semitendinosus)"],
    instructions: [
      "Lie face down on leg curl machine with lever pad against lower calves.",
      "Curl legs up toward glutes as far as possible.",
      "Lower weight back down smoothly.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "standing-calf-raise",
    name: "Standing Machine Calf Raise",
    category: "Legs",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Gastrocnemius", "Soleus"],
    instructions: [
      "Place shoulder pads on shoulders with balls of feet on step block.",
      "Lower heels down for deep calf stretch, then press up high onto toes.",
    ],
    rvsMultiplier: 0.75,
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "Legs",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Dumbbell",
    targetMuscles: ["Quadriceps", "Gluteus Medius", "Hamstrings"],
    instructions: [
      "Place top of rear foot on bench behind you. Hold dumbbells at sides.",
      "Lower hips until front thigh is parallel to floor and rear knee almost touches ground.",
      "Drive up through front heel to return to top.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "overhead-press",
    name: "Barbell Standing Overhead Press",
    category: "Shoulders",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Anterior Deltoids", "Lateral Deltoids", "Triceps", "Upper Chest"],
    instructions: [
      "Grip bar slightly wider than shoulders resting across collarbone.",
      "Brace glutes and core, press bar straight up overhead.",
      "Lock out overhead over shoulders and return down under control.",
    ],
    rvsMultiplier: 1.05,
  },
  {
    id: "seated-dumbbell-press",
    name: "Seated Dumbbell Shoulder Press",
    category: "Shoulders",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Anterior Deltoids", "Triceps", "Trapezius"],
    instructions: [
      "Sit on vertical bench holding dumbbells at ear level with palms forward.",
      "Press dumbbells upward until arms are straight above head.",
      "Lower dumbbells steadily back to ear height.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "Shoulders",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Lateral Deltoids"],
    instructions: [
      "Stand holding dumbbells at sides with slight bend in elbows.",
      "Raise arms out to sides until parallel with floor.",
      "Pause at top, then lower with control.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "face-pulls",
    name: "Cable Rope Face Pulls",
    category: "Shoulders",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Rear Deltoids", "Infraspinatus", "Middle Trapezius"],
    instructions: [
      "Attach rope to upper cable pulley. Stand back with arms extended.",
      "Pull rope towards face while flaring elbows out and rotating hands back.",
      "Squeeze rear delts, then slowly release handle forward.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "front-dumbbell-raise",
    name: "Alternating Dumbbell Front Raise",
    category: "Shoulders",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Anterior Deltoids"],
    instructions: [
      "Stand holding dumbbells in front of thighs.",
      "Raise one dumbbell forward to shoulder height with straight arm.",
      "Lower back down and alternate arms.",
    ],
    rvsMultiplier: 0.75,
  },
  {
    id: "barbell-bicep-curl",
    name: "Standing Barbell Bicep Curl",
    category: "Arms",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Barbell",
    targetMuscles: ["Biceps Brachii", "Brachialis"],
    instructions: [
      "Hold barbell with underhand grip shoulder-width apart.",
      "Curl bar up toward chest while keeping elbows locked to sides.",
      "Lower bar slowly down to full arm extension.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "hammer-curl",
    name: "Dumbbell Hammer Curl",
    category: "Arms",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Brachioradialis", "Biceps Brachii"],
    instructions: [
      "Hold dumbbells at sides with palms facing each other (neutral grip).",
      "Curl weights up while maintaining neutral grip.",
      "Squeeze forearm and biceps, then lower down smoothly.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "tricep-rope-pushdown",
    name: "Cable Tricep Rope Pushdown",
    category: "Arms",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Triceps Brachii (Lateral & Medial Heads)"],
    instructions: [
      "Attach rope to high pulley. Hold ends of rope with elbows tucked to sides.",
      "Extend arms down until fully straight, spreading rope ends apart at bottom.",
      "Slowly allow rope to return up to chest level.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "skull-crusher",
    name: "EZ-Bar Skull Crusher",
    category: "Arms",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Triceps Brachii (Long Head)"],
    instructions: [
      "Lie on flat bench holding EZ-bar over chest with narrow grip.",
      "Bend elbows to lower bar down toward forehead while keeping upper arms vertical.",
      "Extend elbows to press bar back up to starting position.",
    ],
    rvsMultiplier: 0.9,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Abdominal Leg Raise",
    category: "Core",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Rectus Abdominis", "Hip Flexors", "Obliques"],
    instructions: [
      "Hang from pull-up bar with overhand grip and legs straight.",
      "Engage core and raise legs until parallel to floor without swinging.",
      "Lower legs back down slowly.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    category: "Core",
    difficultyRank: 5,
    difficultyLabel: "Master",
    equipment: "Bodyweight",
    targetMuscles: ["Rectus Abdominis", "Transverse Abdominis", "Lats"],
    instructions: [
      "Kneel on floor holding ab wheel handles under shoulders.",
      "Roll wheel forward, extending body horizontally until arms are straight out.",
      "Pull back using abdominal muscles to return to start.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "cable-crunch",
    name: "Kneeling Cable Abdominal Crunch",
    category: "Core",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Rectus Abdominis"],
    instructions: [
      "Kneel below cable pulley holding rope handle behind head.",
      "Flex spine to crunch elbows down toward knees.",
      "Slowly return to upright kneeling position.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "plank-hold",
    name: "Forearm Plank Core Hold",
    category: "Core",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Transverse Abdominis", "Core Stabilizers"],
    instructions: [
      "Place forearms on floor with elbows under shoulders.",
      "Extend legs back and maintain straight body line from head to heels.",
    ],
    rvsMultiplier: 0.7,
  },
  {
    id: "step-jack-cardio",
    name: "Step Jack Plyometric Cardio",
    category: "Cardio",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Quadriceps", "Glutes", "Shoulders", "Core"],
    instructions: [
      "Stand upright with feet together and arms at your sides.",
      "Step right foot out to side while swinging both arms up above head.",
      "Return right foot to center and lower arms, then repeat on left side.",
    ],
    rvsMultiplier: 0.7,
  },
  {
    id: "rowing-machine-ergometer",
    name: "Rowing Machine Ergometer",
    category: "Cardio",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Machine",
    targetMuscles: ["Quads", "Glutes", "Lats", "Biceps", "Cardio"],
    instructions: [
      "Strap feet into rower and grab handle with overhand grip.",
      "Drive back with legs first, then lean back slightly and pull handle to sternum.",
      "Extend arms forward, hinge at hips, and bend knees to return to catch position.",
    ],
    rvsMultiplier: 0.9,
  },
];
