export interface ExerciseDefinition {
  id: string;
  name: string;
  category: "Chest" | "Back" | "Legs" | "Shoulders" | "Arms" | "Core" | "Cardio";
  difficultyRank: number;
  difficultyLabel: "Novice" | "Intermediate" | "Advanced" | "Master";
  equipment: "Barbell" | "Dumbbell" | "Bodyweight" | "Machine" | "Cable";
  targetMuscles: string[];
  instructions: string[];
  rvsMultiplier: number;
}

export const EXERCISE_DATABASE: ExerciseDefinition[] = [
  {
    id: "barbell-bench-press",
    name: "Barbell Flat Bench Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Pectoralis Major", "Triceps Brachii", "Anterior Deltoids"],
    instructions: [
      "Lie flat on the bench with feet planted firmly on the floor. Grip the barbell slightly wider than shoulder-width.",
      "Unrack the bar and lower it under control to the middle of your chest while keeping elbows tucked at a 45-degree angle.",
      "Drive through your feet and press the bar explosively back to starting position without locking out elbows abruptly.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "barbell-incline-bench-press",
    name: "Barbell Incline Bench Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Upper Pectoralis Major", "Anterior Deltoids", "Triceps"],
    instructions: [
      "Set bench to a 30 to 45 degree angle. Unrack the bar and position it over your upper chest.",
      "Lower the bar steadily toward your upper chest right below collarbones.",
      "Press the weight vertically back up to starting position with core tight.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "dumbbell-flat-press",
    name: "Dumbbell Flat Bench Press",
    category: "Chest",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Pectoralis Major", "Triceps", "Anterior Deltoids"],
    instructions: [
      "Sit on flat bench holding dumbbells on knees, then lie back and bring dumbbells to chest level.",
      "Press dumbbells upward until arms are extended above chest.",
      "Lower dumbbells with full control until you feel a comfortable stretch in your chest.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "dumbbell-incline-press",
    name: "Incline Dumbbell Press",
    category: "Chest",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Upper Pectoralis Major", "Anterior Deltoids", "Triceps"],
    instructions: [
      "Lie on 30-degree incline bench with dumbbells held at shoulder width.",
      "Press dumbbells upward until arms are straight, keeping wrists stacked over elbows.",
      "Lower dumbbells slowly until upper arms are parallel with torso.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "chest-dips",
    name: "Chest Dips (Parallel Bars)",
    category: "Chest",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Lower Pectoralis Major", "Triceps Brachii", "Anterior Deltoids"],
    instructions: [
      "Mount parallel dip bars and lock out arms. Lean torso forward approximately 30 degrees.",
      "Lower body by bending elbows until shoulders are slightly lower than elbows.",
      "Push body back up to top locked-out position while squeezing lower chest.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "push-up-standard",
    name: "Standard Push-Up",
    category: "Chest",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Pectoralis Major", "Triceps", "Anterior Deltoids", "Core"],
    instructions: [
      "Place hands on floor shoulder-width apart with body forming a straight plank line from head to heels.",
      "Lower body until chest almost touches the floor, keeping elbows at 45 degrees.",
      "Push back up to starting plank position.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "wide-push-up",
    name: "Wide Grip Push-Up",
    category: "Chest",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Outer Pectoralis Major", "Anterior Deltoids"],
    instructions: [
      "Set hands significantly wider than shoulder-width on floor.",
      "Lower chest until parallel to floor, emphasizing outer chest engagement.",
      "Drive back up smoothly through palms.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "cable-crossover-fly",
    name: "Cable Chest Crossover Fly",
    category: "Chest",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Pectoralis Major (Sternal Head)"],
    instructions: [
      "Set dual cable pulleys at shoulder height and grip handles. Step forward with one foot for balance.",
      "With elbows slightly bent, bring handles together in front of chest in a hugging motion.",
      "Pause and squeeze chest, then allow handles to return back with control.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "barbell-deadlift",
    name: "Barbell Conventional Deadlift",
    category: "Back",
    difficultyRank: 5,
    difficultyLabel: "Master",
    equipment: "Barbell",
    targetMuscles: ["Erector Spinae", "Hamstrings", "Glutes", "Latissimus Dorsi", "Trapezius"],
    instructions: [
      "Stand with feet hip-width apart under the barbell over mid-foot. Hinge at hips to grip bar.",
      "Flatten lower back, engage lats, pull slack out of bar, and take deep breath.",
      "Drive legs into ground to lift bar, standing tall at lockout without leaning back excessively.",
    ],
    rvsMultiplier: 1.25,
  },
  {
    id: "bent-over-barbell-row",
    name: "Bent-Over Barbell Row",
    category: "Back",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius", "Biceps"],
    instructions: [
      "Hinge forward at hips at 45 degrees with knees soft and back flat.",
      "Pull barbell towards lower ribcage while squeezing shoulder blades together.",
      "Lower weight with control without letting torso collapse.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "pull-up",
    name: "Bodyweight Pull-Up (Overhand)",
    category: "Back",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Latissimus Dorsi", "Biceps Brachii", "Rear Deltoids"],
    instructions: [
      "Grip pull-up bar wider than shoulders with knuckles facing you.",
      "Pull chest toward bar by driving elbows down into ribs until chin clears bar.",
      "Lower back down to dead hang under control.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown (Wide Grip)",
    category: "Back",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Latissimus Dorsi", "Rhomboids", "Biceps"],
    instructions: [
      "Sit at pulldown machine and adjust thigh pad. Grip wide bar overhand.",
      "Lean back slightly and pull bar down to upper chest while squeezing lats.",
      "Slowly return bar upward until lats are fully stretched.",
    ],
    rvsMultiplier: 0.9,
  },
  {
    id: "single-arm-dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    category: "Back",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Latissimus Dorsi", "Rhomboids", "Biceps"],
    instructions: [
      "Place same-side knee and hand on flat bench. Hold dumbbell in free hand.",
      "Pull dumbbell up toward hip while driving elbow toward ceiling.",
      "Lower dumbbell with stretch at bottom without rotating torso.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    category: "Back",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Middle Trapezius", "Rhomboids", "Latissimus Dorsi"],
    instructions: [
      "Sit with feet against footrests and knees soft. Grip V-bar handle.",
      "Keep torso upright and pull handle into abdomen while retracting shoulder blades.",
      "Extend arms back out with controlled tempo.",
    ],
    rvsMultiplier: 0.9,
  },
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    category: "Legs",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Quadriceps", "Gluteus Maximus", "Hamstrings", "Core"],
    instructions: [
      "Position bar across upper trapezius muscles. Unrack bar and stand with feet shoulder-width apart.",
      "Hinge hips and bend knees to descend until thighs are parallel to ground or lower.",
      "Drive up through heels and mid-foot to starting position.",
    ],
    rvsMultiplier: 1.15,
  },
  {
    id: "barbell-front-squat",
    name: "Barbell Front Squat",
    category: "Legs",
    difficultyRank: 5,
    difficultyLabel: "Master",
    equipment: "Barbell",
    targetMuscles: ["Quadriceps", "Upper Back", "Core"],
    instructions: [
      "Rest barbell on front deltoids with fingertips under bar and elbows high.",
      "Keep chest tall and squat down deeply between knees.",
      "Drive back up while maintaining high elbow position.",
    ],
    rvsMultiplier: 1.2,
  },
  {
    id: "leg-press-machine",
    name: "Leg Press (45-Degree Machine)",
    category: "Legs",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Quadriceps", "Glutes", "Hamstrings"],
    instructions: [
      "Sit in leg press seat and place feet shoulder-width apart on sled.",
      "Unlatch safety handles and lower sled until knees form 90-degree angle.",
      "Press sled back up without locking out knees completely.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "bulgarian-split-squat",
    name: "Dumbbell Bulgarian Split Squat",
    category: "Legs",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Dumbbell",
    targetMuscles: ["Quadriceps", "Gluteus Medius", "Hamstrings"],
    instructions: [
      "Place rear foot elevated on bench behind you. Hold dumbbells at sides.",
      "Lower front thigh until parallel to ground, keeping front knee aligned over ankle.",
      "Push through front heel to return to top.",
    ],
    rvsMultiplier: 1.1,
  },
  {
    id: "dumbbell-walking-lunge",
    name: "Dumbbell Walking Lunge",
    category: "Legs",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    instructions: [
      "Step forward with right leg and lower hips until both knees bend at 90 degrees.",
      "Drive through front heel to step forward into next lunge with left leg.",
      "Maintain upright torso throughout walking motion.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl (Hamstring)",
    category: "Legs",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Hamstrings (Biceps Femoris)"],
    instructions: [
      "Lie face down on machine with pad against lower calves.",
      "Curl pad upward toward glutes as far as possible.",
      "Lower pad slowly back to extended starting position.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "standing-calf-raise",
    name: "Standing Machine Calf Raise",
    category: "Legs",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Machine",
    targetMuscles: ["Gastrocnemius", "Soleus"],
    instructions: [
      "Place balls of feet on platform with shoulders under pads.",
      "Lower heels down into full calf stretch.",
      "Raise up onto tiptoes as high as possible and squeeze calves.",
    ],
    rvsMultiplier: 0.75,
  },
  {
    id: "overhead-press",
    name: "Barbell Standing Overhead Press",
    category: "Shoulders",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Barbell",
    targetMuscles: ["Anterior Deltoids", "Lateral Deltoids", "Triceps", "Upper Chest"],
    instructions: [
      "Rack bar at collarbone height. Grip bar overhand slightly wider than shoulders.",
      "Press bar straight overhead while squeezing glutes and abs.",
      "Lower bar back down to collarbone under full control.",
    ],
    rvsMultiplier: 1.05,
  },
  {
    id: "dumbbell-seated-shoulder-press",
    name: "Dumbbell Seated Shoulder Press",
    category: "Shoulders",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Anterior Deltoids", "Lateral Deltoids", "Triceps"],
    instructions: [
      "Sit upright on bench. Raise dumbbells to shoulder height palms facing forward.",
      "Press dumbbells overhead until arms are extended overhead.",
      "Lower dumbbells smoothly back to ear height.",
    ],
    rvsMultiplier: 0.95,
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Standing Lateral Raise",
    category: "Shoulders",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Lateral Deltoids"],
    instructions: [
      "Stand holding dumbbells at sides with slight elbow bend.",
      "Raise arms out to sides until parallel to floor.",
      "Lower weights with control without swinging torso.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "arnold-press",
    name: "Dumbbell Seated Arnold Press",
    category: "Shoulders",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Dumbbell",
    targetMuscles: ["Anterior Deltoids", "Lateral Deltoids", "Triceps"],
    instructions: [
      "Sit holding dumbbells in front of chest with palms facing you.",
      "As you press overhead, rotate palms outward 180 degrees so palms face forward at top.",
      "Reverse rotation as you lower back down.",
    ],
    rvsMultiplier: 1.0,
  },
  {
    id: "face-pull-cable",
    name: "Cable Face Pull",
    category: "Shoulders",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Rear Deltoids", "Infraspinatus", "Trapezius"],
    instructions: [
      "Attach rope handle to high cable pulley. Grip rope with thumbs pointing back.",
      "Pull rope straight toward face, separating hands and squeezing rear delts.",
      "Slowly return to start position.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "barbell-bicep-curl",
    name: "Standing Barbell Bicep Curl",
    category: "Arms",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Barbell",
    targetMuscles: ["Biceps Brachii", "Brachialis"],
    instructions: [
      "Stand holding EZ-bar or straight barbell underhand shoulder-width apart.",
      "Curl bar upward toward shoulders keeping elbows pinned at sides.",
      "Squeeze biceps at top, then lower with tempo.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "dumbbell-hammer-curl",
    name: "Standing Dumbbell Hammer Curl",
    category: "Arms",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Dumbbell",
    targetMuscles: ["Brachioradialis", "Biceps Brachii"],
    instructions: [
      "Hold dumbbells at sides with palms facing each other (neutral grip).",
      "Curl weights up while maintaining neutral palm position.",
      "Squeeze forearms and biceps, then lower down.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "tricep-rope-pushdown",
    name: "Cable Tricep Rope Pushdown",
    category: "Arms",
    difficultyRank: 2,
    difficultyLabel: "Novice",
    equipment: "Cable",
    targetMuscles: ["Triceps Brachii"],
    instructions: [
      "Grip rope ends attached to high pulley. Keep elbows locked near ribs.",
      "Push rope down until arms are fully locked out, flaring rope outward.",
      "Return up to 90 degrees with control.",
    ],
    rvsMultiplier: 0.8,
  },
  {
    id: "skullcrusher-triceps",
    name: "Lying EZ-Bar Skullcrusher",
    category: "Arms",
    difficultyRank: 3,
    difficultyLabel: "Intermediate",
    equipment: "Barbell",
    targetMuscles: ["Triceps Brachii (Long Head)"],
    instructions: [
      "Lie on bench holding EZ-bar over chest with arms extended.",
      "Bend elbows to lower bar toward forehead while keeping upper arms vertical.",
      "Extend arms back up to starting lockout.",
    ],
    rvsMultiplier: 0.9,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Abdominal Leg Raise",
    category: "Core",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Rectus Abdominis", "Hip Flexors"],
    instructions: [
      "Hang from pull-up bar with overhand grip.",
      "Raise straight legs up until parallel to floor without swinging.",
      "Lower legs slowly back down.",
    ],
    rvsMultiplier: 0.85,
  },
  {
    id: "plank-hold",
    name: "Isometric Forearm Plank Hold",
    category: "Core",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Transverse Abdominis", "Rectus Abdominis", "Core"],
    instructions: [
      "Rest on forearms and toes with elbows under shoulders.",
      "Hold rigid straight plank line from shoulders to ankles.",
      "Keep glutes and abs engaged continuously.",
    ],
    rvsMultiplier: 0.75,
  },
  {
    id: "step-jack-cardio",
    name: "Step Jack Low Impact Cardio",
    category: "Cardio",
    difficultyRank: 1,
    difficultyLabel: "Novice",
    equipment: "Bodyweight",
    targetMuscles: ["Quadriceps", "Glutes", "Shoulders"],
    instructions: [
      "Stand upright with feet together.",
      "Step right foot out while swinging arms overhead.",
      "Return right foot and repeat with left foot rhythmically.",
    ],
    rvsMultiplier: 0.7,
  },
  {
    id: "burpee-full-body",
    name: "Full Body Burpee",
    category: "Cardio",
    difficultyRank: 4,
    difficultyLabel: "Advanced",
    equipment: "Bodyweight",
    targetMuscles: ["Full Body", "Quads", "Chest", "Core"],
    instructions: [
      "Drop from standing into a squat, kick feet back into plank, perform a push-up.",
      "Pop feet back to hands and jump explosively into the air with hands overhead.",
      "Land softly and repeat continuously.",
    ],
    rvsMultiplier: 1.15,
  },
];
